[versions]
kotlin = "2.1.0"
http4k = "5.44.0.0"
junit = "5.11.4"
linter = "5.0.1"

[libraries]
http4k-bom = { module = "org.http4k:http4k-bom", version.ref = "http4k" }
http4k-client-okhttp = { module = "org.http4k:http4k-client-okhttp", version.ref = "http4k" }
http4k-core = { module = "org.http4k:http4k-core", version.ref = "http4k" }
http4k-format-jackson-yaml = { module = "org.http4k:http4k-format-jackson-yaml", version.ref = "http4k" }
http4k-format-jackson = { module = "org.http4k:http4k-format-jackson", version.ref = "http4k" }
http4k-server-undertow = { module = "org.http4k:http4k-server-undertow", version.ref = "http4k" }
http4k-testing-approval = { module = "org.http4k:http4k-testing-approval", version.ref = "http4k" }
http4k-testing-hamkrest = { module = "org.http4k:http4k-testing-hamkrest", version.ref = "http4k" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[plugins]
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "linter" }
